-- -------------------------------------------------------------
-- 
-- File Name: /home/apurvan/BBU/CRC_encoder_export/hdlsrc/ltehdlCRCEncoderModel/CRCGenCompute.vhd
-- Created: 2019-12-07 18:56:55
-- 
-- Generated by MATLAB 9.6 and HDL Coder 3.14
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: CRCGenCompute
-- Source Path: ltehdlCRCEncoderModel/HDL Algorithm/CRC Encoder/CRCGenerator/CRCGenCompute
-- Hierarchy Level: 3
-- 
-- Compute the CRC CheckSum
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY CRCGenCompute IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        datainReg                         :   IN    std_logic_vector(0 TO 7);  -- ufix1 [8]
        validIn                           :   IN    std_logic;  -- ufix1
        processMsg                        :   IN    std_logic;  -- ufix1
        padZero                           :   IN    std_logic;  -- ufix1
        counter                           :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        regClr                            :   IN    std_logic;  -- ufix1
        crcChecksum                       :   OUT   std_logic_vector(0 TO 23)  -- ufix1 [24]
        );
END CRCGenCompute;


ARCHITECTURE rtl OF CRCGenCompute IS

  -- Signals
  SIGNAL counter_unsigned                 : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL xoredSel                         : std_logic;  -- ufix1
  SIGNAL dvalidin                         : std_logic;  -- ufix1
  SIGNAL tcsSel                           : std_logic;  -- ufix1
  SIGNAL csSel                            : std_logic;  -- ufix1
  SIGNAL checksumRst                      : std_logic;  -- ufix1
  SIGNAL rpadZero                         : std_logic;  -- ufix1
  SIGNAL dataSel                          : std_logic;  -- ufix1
  SIGNAL inputzeros                       : std_logic_vector(0 TO 15);  -- ufix1 [16]
  SIGNAL padingzeros                      : std_logic_vector(0 TO 23);  -- ufix1 [24]
  SIGNAL datamux                          : std_logic_vector(0 TO 23);  -- ufix1 [24]
  SIGNAL datacpt                          : std_logic_vector(0 TO 23);  -- ufix1 [24]
  SIGNAL datacpt_23                       : std_logic;  -- ufix1
  SIGNAL datacpt_22                       : std_logic;  -- ufix1
  SIGNAL datacpt_21                       : std_logic;  -- ufix1
  SIGNAL datacpt_20                       : std_logic;  -- ufix1
  SIGNAL datacpt_19                       : std_logic;  -- ufix1
  SIGNAL datacpt_18                       : std_logic;  -- ufix1
  SIGNAL datacpt_17                       : std_logic;  -- ufix1
  SIGNAL datacpt_16                       : std_logic;  -- ufix1
  SIGNAL datacpt_15                       : std_logic;  -- ufix1
  SIGNAL datacpt_14                       : std_logic;  -- ufix1
  SIGNAL datacpt_13                       : std_logic;  -- ufix1
  SIGNAL datacpt_12                       : std_logic;  -- ufix1
  SIGNAL datacpt_11                       : std_logic;  -- ufix1
  SIGNAL datacpt_10                       : std_logic;  -- ufix1
  SIGNAL datacpt_9                        : std_logic;  -- ufix1
  SIGNAL datacpt_8                        : std_logic;  -- ufix1
  SIGNAL datacpt_7                        : std_logic;  -- ufix1
  SIGNAL datacpt_6                        : std_logic;  -- ufix1
  SIGNAL datacpt_5                        : std_logic;  -- ufix1
  SIGNAL datacpt_4                        : std_logic;  -- ufix1
  SIGNAL datacpt_3                        : std_logic;  -- ufix1
  SIGNAL datacpt_2                        : std_logic;  -- ufix1
  SIGNAL datacpt_1                        : std_logic;  -- ufix1
  SIGNAL datacpt_0                        : std_logic;  -- ufix1
  SIGNAL finalXorValue                    : std_logic_vector(0 TO 23);  -- ufix1 [24]
  SIGNAL finalXorValue_0                  : std_logic;  -- ufix1
  SIGNAL finalXorValue_1                  : std_logic;  -- ufix1
  SIGNAL finalXorValue_2                  : std_logic;  -- ufix1
  SIGNAL finalXorValue_3                  : std_logic;  -- ufix1
  SIGNAL finalXorValue_4                  : std_logic;  -- ufix1
  SIGNAL finalXorValue_5                  : std_logic;  -- ufix1
  SIGNAL finalXorValue_6                  : std_logic;  -- ufix1
  SIGNAL finalXorValue_7                  : std_logic;  -- ufix1
  SIGNAL finalXorValue_8                  : std_logic;  -- ufix1
  SIGNAL finalXorValue_9                  : std_logic;  -- ufix1
  SIGNAL finalXorValue_10                 : std_logic;  -- ufix1
  SIGNAL finalXorValue_11                 : std_logic;  -- ufix1
  SIGNAL finalXorValue_12                 : std_logic;  -- ufix1
  SIGNAL finalXorValue_13                 : std_logic;  -- ufix1
  SIGNAL finalXorValue_14                 : std_logic;  -- ufix1
  SIGNAL finalXorValue_15                 : std_logic;  -- ufix1
  SIGNAL finalXorValue_16                 : std_logic;  -- ufix1
  SIGNAL finalXorValue_17                 : std_logic;  -- ufix1
  SIGNAL finalXorValue_18                 : std_logic;  -- ufix1
  SIGNAL finalXorValue_19                 : std_logic;  -- ufix1
  SIGNAL finalXorValue_20                 : std_logic;  -- ufix1
  SIGNAL finalXorValue_21                 : std_logic;  -- ufix1
  SIGNAL finalXorValue_22                 : std_logic;  -- ufix1
  SIGNAL finalXorValue_23                 : std_logic;  -- ufix1
  SIGNAL newChecksum                      : std_logic_vector(0 TO 23);  -- ufix1 [24]
  SIGNAL newChecksum_0                    : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_23               : std_logic;  -- ufix1
  SIGNAL newChecksum_1                    : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_22               : std_logic;  -- ufix1
  SIGNAL newChecksum_2                    : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_21               : std_logic;  -- ufix1
  SIGNAL newChecksum_3                    : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_20               : std_logic;  -- ufix1
  SIGNAL newChecksum_4                    : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_19               : std_logic;  -- ufix1
  SIGNAL newChecksum_5                    : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_18               : std_logic;  -- ufix1
  SIGNAL newChecksum_6                    : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_17               : std_logic;  -- ufix1
  SIGNAL newChecksum_7                    : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_16               : std_logic;  -- ufix1
  SIGNAL newChecksum_8                    : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_15               : std_logic;  -- ufix1
  SIGNAL newChecksum_9                    : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_14               : std_logic;  -- ufix1
  SIGNAL newChecksum_10                   : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_13               : std_logic;  -- ufix1
  SIGNAL newChecksum_11                   : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_12               : std_logic;  -- ufix1
  SIGNAL newChecksum_12                   : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_11               : std_logic;  -- ufix1
  SIGNAL newChecksum_13                   : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_10               : std_logic;  -- ufix1
  SIGNAL newChecksum_14                   : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_9                : std_logic;  -- ufix1
  SIGNAL newChecksum_15                   : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_8                : std_logic;  -- ufix1
  SIGNAL newChecksum_16                   : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_7                : std_logic;  -- ufix1
  SIGNAL newChecksum_17                   : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_6                : std_logic;  -- ufix1
  SIGNAL newChecksum_18                   : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_5                : std_logic;  -- ufix1
  SIGNAL newChecksum_19                   : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_4                : std_logic;  -- ufix1
  SIGNAL newChecksum_20                   : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_3                : std_logic;  -- ufix1
  SIGNAL newChecksum_21                   : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_2                : std_logic;  -- ufix1
  SIGNAL newChecksum_22                   : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_1                : std_logic;  -- ufix1
  SIGNAL newChecksum_23                   : std_logic;  -- ufix1
  SIGNAL refelctCheckSum_0                : std_logic;  -- ufix1
  SIGNAL xoredChecksum                    : std_logic_vector(0 TO 23);  -- ufix1 [24]
  SIGNAL checksumReg                      : std_logic_vector(0 TO 23);  -- ufix1 [24]
  SIGNAL checksumReg_15                   : std_logic;  -- ufix1
  SIGNAL checksumReg_23                   : std_logic;  -- ufix1
  SIGNAL checksumReg_22                   : std_logic;  -- ufix1
  SIGNAL checksumReg_21                   : std_logic;  -- ufix1
  SIGNAL checksumReg_20                   : std_logic;  -- ufix1
  SIGNAL checksumReg_19                   : std_logic;  -- ufix1
  SIGNAL checksumReg_18                   : std_logic;  -- ufix1
  SIGNAL checksumReg_17                   : std_logic;  -- ufix1
  SIGNAL checksumReg_16                   : std_logic;  -- ufix1
  SIGNAL tcs_entry23                      : std_logic;  -- ufix1
  SIGNAL checksumReg_14                   : std_logic;  -- ufix1
  SIGNAL tcs_entry22                      : std_logic;  -- ufix1
  SIGNAL checksumReg_13                   : std_logic;  -- ufix1
  SIGNAL tcs_entry21                      : std_logic;  -- ufix1
  SIGNAL checksumReg_12                   : std_logic;  -- ufix1
  SIGNAL tcs_entry20                      : std_logic;  -- ufix1
  SIGNAL checksumReg_11                   : std_logic;  -- ufix1
  SIGNAL tcs_entry19                      : std_logic;  -- ufix1
  SIGNAL checksumReg_10                   : std_logic;  -- ufix1
  SIGNAL tcs_entry18                      : std_logic;  -- ufix1
  SIGNAL checksumReg_9                    : std_logic;  -- ufix1
  SIGNAL tcs_entry17                      : std_logic;  -- ufix1
  SIGNAL checksumReg_8                    : std_logic;  -- ufix1
  SIGNAL tcs_entry16                      : std_logic;  -- ufix1
  SIGNAL checksumReg_7                    : std_logic;  -- ufix1
  SIGNAL tcs_entry15                      : std_logic;  -- ufix1
  SIGNAL checksumReg_6                    : std_logic;  -- ufix1
  SIGNAL tcs_entry14                      : std_logic;  -- ufix1
  SIGNAL checksumReg_5                    : std_logic;  -- ufix1
  SIGNAL tcs_entry13                      : std_logic;  -- ufix1
  SIGNAL checksumReg_4                    : std_logic;  -- ufix1
  SIGNAL tcs_entry12                      : std_logic;  -- ufix1
  SIGNAL checksumReg_3                    : std_logic;  -- ufix1
  SIGNAL tcs_entry11                      : std_logic;  -- ufix1
  SIGNAL checksumReg_2                    : std_logic;  -- ufix1
  SIGNAL tcs_entry10                      : std_logic;  -- ufix1
  SIGNAL checksumReg_1                    : std_logic;  -- ufix1
  SIGNAL tcs_entry9                       : std_logic;  -- ufix1
  SIGNAL checksumReg_0                    : std_logic;  -- ufix1
  SIGNAL tcs_entry8                       : std_logic;  -- ufix1
  SIGNAL tcs_entry7                       : std_logic;  -- ufix1
  SIGNAL tcs_entry6                       : std_logic;  -- ufix1
  SIGNAL tcs_entry5                       : std_logic;  -- ufix1
  SIGNAL tcs_entry4                       : std_logic;  -- ufix1
  SIGNAL tcs_entry3                       : std_logic;  -- ufix1
  SIGNAL tcs_entry2                       : std_logic;  -- ufix1
  SIGNAL tcs_entry1                       : std_logic;  -- ufix1
  SIGNAL tcs_entry0                       : std_logic;  -- ufix1
  SIGNAL tchecksum                        : std_logic_vector(0 TO 23);  -- ufix1 [24]
  SIGNAL finalChecksum                    : std_logic_vector(0 TO 23);  -- ufix1 [24]

BEGIN
  counter_unsigned <= unsigned(counter);

  
  xoredSel <= '1' WHEN counter_unsigned = to_unsigned(16#2#, 2) ELSE
      '0';

  validin_register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      dvalidin <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        dvalidin <= validIn;
      END IF;
    END IF;
  END PROCESS validin_register_process;


  tcsSel <= processMsg AND dvalidin;

  csSel <= tcsSel OR padZero;

  checksumRst <= xoredSel OR regClr;

  rpadZero <=  NOT padZero;

  -- Selection signal: Select input data or pad zeros
  dataSel <= rpadZero AND dvalidin;

  inputzeros(0) <= '0';
  inputzeros(1) <= '0';
  inputzeros(2) <= '0';
  inputzeros(3) <= '0';
  inputzeros(4) <= '0';
  inputzeros(5) <= '0';
  inputzeros(6) <= '0';
  inputzeros(7) <= '0';
  inputzeros(8) <= '0';
  inputzeros(9) <= '0';
  inputzeros(10) <= '0';
  inputzeros(11) <= '0';
  inputzeros(12) <= '0';
  inputzeros(13) <= '0';
  inputzeros(14) <= '0';
  inputzeros(15) <= '0';

  -- Padding zeros
  padingzeros(0) <= '0';
  padingzeros(1) <= '0';
  padingzeros(2) <= '0';
  padingzeros(3) <= '0';
  padingzeros(4) <= '0';
  padingzeros(5) <= '0';
  padingzeros(6) <= '0';
  padingzeros(7) <= '0';
  padingzeros(8) <= '0';
  padingzeros(9) <= '0';
  padingzeros(10) <= '0';
  padingzeros(11) <= '0';
  padingzeros(12) <= '0';
  padingzeros(13) <= '0';
  padingzeros(14) <= '0';
  padingzeros(15) <= '0';
  padingzeros(16) <= '0';
  padingzeros(17) <= '0';
  padingzeros(18) <= '0';
  padingzeros(19) <= '0';
  padingzeros(20) <= '0';
  padingzeros(21) <= '0';
  padingzeros(22) <= '0';
  padingzeros(23) <= '0';

  -- Prepare inputs for parallel CRC computation
  datamux(0) <= inputzeros(0);
  datamux(1) <= inputzeros(1);
  datamux(2) <= inputzeros(2);
  datamux(3) <= inputzeros(3);
  datamux(4) <= inputzeros(4);
  datamux(5) <= inputzeros(5);
  datamux(6) <= inputzeros(6);
  datamux(7) <= inputzeros(7);
  datamux(8) <= inputzeros(8);
  datamux(9) <= inputzeros(9);
  datamux(10) <= inputzeros(10);
  datamux(11) <= inputzeros(11);
  datamux(12) <= inputzeros(12);
  datamux(13) <= inputzeros(13);
  datamux(14) <= inputzeros(14);
  datamux(15) <= inputzeros(15);
  datamux(16) <= datainReg(0);
  datamux(17) <= datainReg(1);
  datamux(18) <= datainReg(2);
  datamux(19) <= datainReg(3);
  datamux(20) <= datainReg(4);
  datamux(21) <= datainReg(5);
  datamux(22) <= datainReg(6);
  datamux(23) <= datainReg(7);

  -- Switch between input data and padded zeros
  
  datacpt <= padingzeros WHEN dataSel = '0' ELSE
      datamux;

  datacpt_23 <= datacpt(23);

  datacpt_22 <= datacpt(22);

  datacpt_21 <= datacpt(21);

  datacpt_20 <= datacpt(20);

  datacpt_19 <= datacpt(19);

  datacpt_18 <= datacpt(18);

  datacpt_17 <= datacpt(17);

  datacpt_16 <= datacpt(16);

  datacpt_15 <= datacpt(15);

  datacpt_14 <= datacpt(14);

  datacpt_13 <= datacpt(13);

  datacpt_12 <= datacpt(12);

  datacpt_11 <= datacpt(11);

  datacpt_10 <= datacpt(10);

  datacpt_9 <= datacpt(9);

  datacpt_8 <= datacpt(8);

  datacpt_7 <= datacpt(7);

  datacpt_6 <= datacpt(6);

  datacpt_5 <= datacpt(5);

  datacpt_4 <= datacpt(4);

  datacpt_3 <= datacpt(3);

  datacpt_2 <= datacpt(2);

  datacpt_1 <= datacpt(1);

  datacpt_0 <= datacpt(0);

  -- Compute finalXor
  finalXorValue(0) <= '0';
  finalXorValue(1) <= '0';
  finalXorValue(2) <= '0';
  finalXorValue(3) <= '0';
  finalXorValue(4) <= '0';
  finalXorValue(5) <= '0';
  finalXorValue(6) <= '0';
  finalXorValue(7) <= '0';
  finalXorValue(8) <= '0';
  finalXorValue(9) <= '0';
  finalXorValue(10) <= '0';
  finalXorValue(11) <= '0';
  finalXorValue(12) <= '0';
  finalXorValue(13) <= '0';
  finalXorValue(14) <= '0';
  finalXorValue(15) <= '0';
  finalXorValue(16) <= '0';
  finalXorValue(17) <= '0';
  finalXorValue(18) <= '1';
  finalXorValue(19) <= '1';
  finalXorValue(20) <= '0';
  finalXorValue(21) <= '0';
  finalXorValue(22) <= '1';
  finalXorValue(23) <= '0';

  finalXorValue_0 <= finalXorValue(0);

  finalXorValue_1 <= finalXorValue(1);

  finalXorValue_2 <= finalXorValue(2);

  finalXorValue_3 <= finalXorValue(3);

  finalXorValue_4 <= finalXorValue(4);

  finalXorValue_5 <= finalXorValue(5);

  finalXorValue_6 <= finalXorValue(6);

  finalXorValue_7 <= finalXorValue(7);

  finalXorValue_8 <= finalXorValue(8);

  finalXorValue_9 <= finalXorValue(9);

  finalXorValue_10 <= finalXorValue(10);

  finalXorValue_11 <= finalXorValue(11);

  finalXorValue_12 <= finalXorValue(12);

  finalXorValue_13 <= finalXorValue(13);

  finalXorValue_14 <= finalXorValue(14);

  finalXorValue_15 <= finalXorValue(15);

  finalXorValue_16 <= finalXorValue(16);

  finalXorValue_17 <= finalXorValue(17);

  finalXorValue_18 <= finalXorValue(18);

  finalXorValue_19 <= finalXorValue(19);

  finalXorValue_20 <= finalXorValue(20);

  finalXorValue_21 <= finalXorValue(21);

  finalXorValue_22 <= finalXorValue(22);

  finalXorValue_23 <= finalXorValue(23);

  newChecksum_0 <= newChecksum(0);

  refelctCheckSum_23 <= newChecksum_0 XOR finalXorValue_23;

  newChecksum_1 <= newChecksum(1);

  refelctCheckSum_22 <= newChecksum_1 XOR finalXorValue_22;

  newChecksum_2 <= newChecksum(2);

  refelctCheckSum_21 <= newChecksum_2 XOR finalXorValue_21;

  newChecksum_3 <= newChecksum(3);

  refelctCheckSum_20 <= newChecksum_3 XOR finalXorValue_20;

  newChecksum_4 <= newChecksum(4);

  refelctCheckSum_19 <= newChecksum_4 XOR finalXorValue_19;

  newChecksum_5 <= newChecksum(5);

  refelctCheckSum_18 <= newChecksum_5 XOR finalXorValue_18;

  newChecksum_6 <= newChecksum(6);

  refelctCheckSum_17 <= newChecksum_6 XOR finalXorValue_17;

  newChecksum_7 <= newChecksum(7);

  refelctCheckSum_16 <= newChecksum_7 XOR finalXorValue_16;

  newChecksum_8 <= newChecksum(8);

  refelctCheckSum_15 <= newChecksum_8 XOR finalXorValue_15;

  newChecksum_9 <= newChecksum(9);

  refelctCheckSum_14 <= newChecksum_9 XOR finalXorValue_14;

  newChecksum_10 <= newChecksum(10);

  refelctCheckSum_13 <= newChecksum_10 XOR finalXorValue_13;

  newChecksum_11 <= newChecksum(11);

  refelctCheckSum_12 <= newChecksum_11 XOR finalXorValue_12;

  newChecksum_12 <= newChecksum(12);

  refelctCheckSum_11 <= newChecksum_12 XOR finalXorValue_11;

  newChecksum_13 <= newChecksum(13);

  refelctCheckSum_10 <= newChecksum_13 XOR finalXorValue_10;

  newChecksum_14 <= newChecksum(14);

  refelctCheckSum_9 <= newChecksum_14 XOR finalXorValue_9;

  newChecksum_15 <= newChecksum(15);

  refelctCheckSum_8 <= newChecksum_15 XOR finalXorValue_8;

  newChecksum_16 <= newChecksum(16);

  refelctCheckSum_7 <= newChecksum_16 XOR finalXorValue_7;

  newChecksum_17 <= newChecksum(17);

  refelctCheckSum_6 <= newChecksum_17 XOR finalXorValue_6;

  newChecksum_18 <= newChecksum(18);

  refelctCheckSum_5 <= newChecksum_18 XOR finalXorValue_5;

  newChecksum_19 <= newChecksum(19);

  refelctCheckSum_4 <= newChecksum_19 XOR finalXorValue_4;

  newChecksum_20 <= newChecksum(20);

  refelctCheckSum_3 <= newChecksum_20 XOR finalXorValue_3;

  newChecksum_21 <= newChecksum(21);

  refelctCheckSum_2 <= newChecksum_21 XOR finalXorValue_2;

  newChecksum_22 <= newChecksum(22);

  refelctCheckSum_1 <= newChecksum_22 XOR finalXorValue_1;

  -- Reflect Checksum and make checksum LSB first
  newChecksum_23 <= newChecksum(23);

  refelctCheckSum_0 <= newChecksum_23 XOR finalXorValue_0;

  xoredChecksum(0) <= refelctCheckSum_0;
  xoredChecksum(1) <= refelctCheckSum_1;
  xoredChecksum(2) <= refelctCheckSum_2;
  xoredChecksum(3) <= refelctCheckSum_3;
  xoredChecksum(4) <= refelctCheckSum_4;
  xoredChecksum(5) <= refelctCheckSum_5;
  xoredChecksum(6) <= refelctCheckSum_6;
  xoredChecksum(7) <= refelctCheckSum_7;
  xoredChecksum(8) <= refelctCheckSum_8;
  xoredChecksum(9) <= refelctCheckSum_9;
  xoredChecksum(10) <= refelctCheckSum_10;
  xoredChecksum(11) <= refelctCheckSum_11;
  xoredChecksum(12) <= refelctCheckSum_12;
  xoredChecksum(13) <= refelctCheckSum_13;
  xoredChecksum(14) <= refelctCheckSum_14;
  xoredChecksum(15) <= refelctCheckSum_15;
  xoredChecksum(16) <= refelctCheckSum_16;
  xoredChecksum(17) <= refelctCheckSum_17;
  xoredChecksum(18) <= refelctCheckSum_18;
  xoredChecksum(19) <= refelctCheckSum_19;
  xoredChecksum(20) <= refelctCheckSum_20;
  xoredChecksum(21) <= refelctCheckSum_21;
  xoredChecksum(22) <= refelctCheckSum_22;
  xoredChecksum(23) <= refelctCheckSum_23;

  checksumReg_15 <= checksumReg(15);

  -- Compute checksum element24
  tcs_entry23 <= datacpt_0 XOR (checksumReg_15 XOR (checksumReg_16 XOR (checksumReg_17 XOR (checksumReg_18 XOR (checksumReg_19 XOR (checksumReg_20 XOR (checksumReg_21 XOR (checksumReg_23 XOR checksumReg_22))))))));

  checksumReg_14 <= checksumReg(14);

  -- Compute checksum element23
  tcs_entry22 <= checksumReg_14 XOR datacpt_1;

  checksumReg_13 <= checksumReg(13);

  -- Compute checksum element22
  tcs_entry21 <= checksumReg_13 XOR datacpt_2;

  checksumReg_12 <= checksumReg(12);

  -- Compute checksum element21
  tcs_entry20 <= checksumReg_12 XOR datacpt_3;

  checksumReg_11 <= checksumReg(11);

  -- Compute checksum element20
  tcs_entry19 <= checksumReg_11 XOR datacpt_4;

  checksumReg_10 <= checksumReg(10);

  -- Compute checksum element19
  tcs_entry18 <= checksumReg_10 XOR datacpt_5;

  checksumReg_9 <= checksumReg(9);

  -- Compute checksum element18
  tcs_entry17 <= checksumReg_9 XOR datacpt_6;

  checksumReg_8 <= checksumReg(8);

  -- Compute checksum element17
  tcs_entry16 <= checksumReg_8 XOR datacpt_7;

  checksumReg_7 <= checksumReg(7);

  -- Compute checksum element16
  tcs_entry15 <= checksumReg_7 XOR datacpt_8;

  checksumReg_6 <= checksumReg(6);

  -- Compute checksum element15
  tcs_entry14 <= checksumReg_6 XOR datacpt_9;

  checksumReg_5 <= checksumReg(5);

  -- Compute checksum element14
  tcs_entry13 <= datacpt_10 XOR (checksumReg_23 XOR checksumReg_5);

  checksumReg_4 <= checksumReg(4);

  -- Compute checksum element13
  tcs_entry12 <= datacpt_11 XOR (checksumReg_22 XOR checksumReg_4);

  checksumReg_3 <= checksumReg(3);

  -- Compute checksum element12
  tcs_entry11 <= datacpt_12 XOR (checksumReg_21 XOR checksumReg_3);

  checksumReg_2 <= checksumReg(2);

  -- Compute checksum element11
  tcs_entry10 <= datacpt_13 XOR (checksumReg_20 XOR checksumReg_2);

  checksumReg_1 <= checksumReg(1);

  -- Compute checksum element10
  tcs_entry9 <= datacpt_14 XOR (checksumReg_19 XOR checksumReg_1);

  checksumReg_0 <= checksumReg(0);

  -- Compute checksum element9
  tcs_entry8 <= datacpt_15 XOR (checksumReg_0 XOR (checksumReg_23 XOR checksumReg_18));

  -- Compute checksum element8
  tcs_entry7 <= datacpt_16 XOR (checksumReg_22 XOR checksumReg_17);

  -- Compute checksum element7
  tcs_entry6 <= datacpt_17 XOR (checksumReg_21 XOR checksumReg_16);

  -- Compute checksum element6
  tcs_entry5 <= datacpt_18 XOR (checksumReg_16 XOR (checksumReg_17 XOR (checksumReg_18 XOR (checksumReg_19 XOR (checksumReg_21 XOR (checksumReg_23 XOR checksumReg_22))))));

  -- Compute checksum element5
  tcs_entry4 <= checksumReg_19 XOR datacpt_19;

  -- Compute checksum element4
  tcs_entry3 <= checksumReg_18 XOR datacpt_20;

  -- Compute checksum element3
  tcs_entry2 <= checksumReg_17 XOR datacpt_21;

  -- Compute checksum element2
  tcs_entry1 <= checksumReg_16 XOR datacpt_22;

  checksumReg_16 <= checksumReg(16);

  checksumReg_17 <= checksumReg(17);

  checksumReg_18 <= checksumReg(18);

  checksumReg_19 <= checksumReg(19);

  checksumReg_20 <= checksumReg(20);

  checksumReg_21 <= checksumReg(21);

  checksumReg_22 <= checksumReg(22);

  checksumReg_23 <= checksumReg(23);

  -- Compute checksum element1
  -- 
  -- Checksum selection signal
  tcs_entry0 <= datacpt_23 XOR (checksumReg_16 XOR (checksumReg_17 XOR (checksumReg_18 XOR (checksumReg_19 XOR (checksumReg_20 XOR (checksumReg_21 XOR (checksumReg_23 XOR checksumReg_22)))))));

  tchecksum(0) <= tcs_entry0;
  tchecksum(1) <= tcs_entry1;
  tchecksum(2) <= tcs_entry2;
  tchecksum(3) <= tcs_entry3;
  tchecksum(4) <= tcs_entry4;
  tchecksum(5) <= tcs_entry5;
  tchecksum(6) <= tcs_entry6;
  tchecksum(7) <= tcs_entry7;
  tchecksum(8) <= tcs_entry8;
  tchecksum(9) <= tcs_entry9;
  tchecksum(10) <= tcs_entry10;
  tchecksum(11) <= tcs_entry11;
  tchecksum(12) <= tcs_entry12;
  tchecksum(13) <= tcs_entry13;
  tchecksum(14) <= tcs_entry14;
  tchecksum(15) <= tcs_entry15;
  tchecksum(16) <= tcs_entry16;
  tchecksum(17) <= tcs_entry17;
  tchecksum(18) <= tcs_entry18;
  tchecksum(19) <= tcs_entry19;
  tchecksum(20) <= tcs_entry20;
  tchecksum(21) <= tcs_entry21;
  tchecksum(22) <= tcs_entry22;
  tchecksum(23) <= tcs_entry23;

  checksum_register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      checksumReg <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        IF checksumRst = '1' THEN
          checksumReg <= (OTHERS => '0');
        ELSE 
          checksumReg <= finalChecksum;
        END IF;
      END IF;
    END IF;
  END PROCESS checksum_register_process;


  -- Update checksum register for valid inputs
  
  newChecksum <= checksumReg WHEN csSel = '0' ELSE
      tchecksum;

  -- Xor after computing the checksum
  
  finalChecksum <= newChecksum WHEN xoredSel = '0' ELSE
      xoredChecksum;

  -- 1
  outputchecksum_register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      crcChecksum <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' AND xoredSel = '1' THEN
        crcChecksum <= finalChecksum;
      END IF;
    END IF;
  END PROCESS outputchecksum_register_process;


END rtl;

